version: "3.7"

services:
  bot:
    build: .
    container_name: bot_nagios_container
    restart: always
    command: python bot.py
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.110.0/24